baseURL: https://dashbook.ml/
languageCode: en-us
title: Dashbook.ml Predictive Analysis | Dashboard ML for Centralized Predictive Analytics
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
- dashboard
- Notebook
- dashbook

markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Dashbook is SaaS platform to centralized Prediction Analysis in one dashboard
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/dashbooklogov1.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Dashboard + Notebook
    # Hero subtitle (optional)
    subtitle: Analytics dashboard for machine learning model
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://dashbook-app.ml/signin"
    # Hero image (from static/images/___)
    image: illustrations/undraw_data_trends.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    #- systek
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  # - title: Features
  #   url: /
  # - title: Pricing
  #   url: /
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  - title: Log in
    url: https://www.dashbook-app.ml/signin
  - title: Sign up
    url: https://www.dashbook-app.ml/signup
    button: true
  section1:
    title: Features
    subtitle: 
    tiles:
    - title: Continuous prediction
      icon: growth_analytics
      text: Continous ML inference as new data enters
      url: /
      buttonText: Free trial
    - title: Database friendly
      icon: server
      text: Connect to your existing database
      url: /
      buttonText: Get started
    - title: Responsive
      icon: devices
      text: View your dashboard in different devices
      url: /
      buttonText: Get started
  # section2: 
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #   - title: Powerful and unified interface
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-globe
  #   - title: Cross-device synchronisation
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: doc-sync
  #   - title: Nomad system
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: mobile-feed
  section3:
    title: Centralized dashboard
    subtitle: for all machine learning prediction
    image: illustrations/mockups/dashboard.png
    buttonText: Get started
    buttonLink: "https://dashbookapp.onrender.com/signin"
  # section4: 
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: dashbooklogov1.png
    # Social Media Title
    # socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # socialmedia:
    #   # Icons are from Font Awesome
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    bulmalogo: false
    quicklinks:
      # column1:
      #   title: "Product"
      #   links:
        # - text: Discover features
        #   link: /
        # - text: Why choose our product?
        #   link: /
        # - text: Compare features
        #   link: /
        # - text: Our roadmap
        #   link: /
      # column2:
      #   title: "Docs"
      #   links:
        # - text: Get started
        #   link: /
        # - text: User guides
        #   link: /
        # - text: Admin guide
        #   link: /
        # - text: Developers
        #   link: /
      # column3:
      #   title: "Blog"
      #   links:
        # - text: Tech articles
        #   link: /
